[project]
name = "mypackage"
version = "0.0.1"
dependencies = [
    "Jinja2",
]

[project.scripts]
cli-name = "src.main:main"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
mypkg = [".j2", "templates/*.j2"]
